version: '3.9'
services:
  eureka-server:
    image: eureka-server
    build: eureka-server
    container_name: eureka_server_container
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway
    build: api-gateway
    container_name: api_gateway_container
    ports:
      - "9090:9090"
    environment:
      - NS_SERVER_URI=http://ns-server:8085
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - ns-server
    links:
      - eureka-server

  ns-server:
    image: ns-server
    build: ns-server
    container_name: server_container
    ports:
      - "8085:8085"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    links:
      - eureka-server
