version: '3.9'
services:
  eureka-server:
    image: eureka-server
    build: eureka-server
    container_name: eureka_server_container
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway
    build: api-gateway
    container_name: api_gateway_container
    ports:
      - "9090:9090"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
        - JWT_SECRET=ecf1222c-88fd-47f3-988f-bdd78bade1ad
        - NS_SERVER_URI=http://ns-server:8085
        - AUTH_SERVER_URI=http://auth-server:8090
    depends_on:
      - eureka-server
      - ns-server
      - auth-server
    links:
      - eureka-server

  ns-server:
    image: ns-server
    build: ns-server
    container_name: ns_server_container
    ports:
      - "8085:8085"
    environment:
        - JWT_SECRET=ecf1222c-88fd-47f3-988f-bdd78bade1ad
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    links:
      - eureka-server

  auth-server:
    image: auth-server
    build: auth-server
    container_name: auth_server_container
    hostname: auth-server
    expose:
      - "8090"
    environment:
        - JWT_SECRET=ecf1222c-88fd-47f3-988f-bdd78bade1ad
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    restart: always
    depends_on:
      - eureka-server
    links:
      - eureka-server

  redis:
    image: 'redis:latest'
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "6379"
