server:
  port: 8085
spring:
  application:
    name: ns-server

jwt:
  secret: ecf1222c-88fd-47f3-988f-bdd78bade1ad

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/