server:
  port: 8085
spring:
  application:
    name: ns-server
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/