server:
  port: 8090
  error:
    include-stacktrace: never

spring:
  application:
    name: auth-server

jwt:
  secret: ecf1222c-88fd-47f3-988f-bdd78bade1ad

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
