server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: ns-server
          uri: http://localhost:8085
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        - id: auth-server
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
          filters:
              - StripPrefix=0
  data:
    redis:
      host: redis
      port: 6379
jwt:
  secret: ecf1222c-88fd-47f3-988f-bdd78bade1ad

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
