server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: ns-server
          uri: ${NS_SERVER_URI}
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                  redis-rate-limiter.replenishRate: 30
                  redis-rate-limiter.burstCapacity: 10
                  redis-rate-limiter.requestedTokens: 5
        - id: auth-server
          uri: ${AUTH_SERVER_URI}
          predicates:
            - Path=/auth/**
          filters:
              - StripPrefix=0
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
