server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ns-server
          uri: http://localhost:9090
          predicates:
            - Path=/notifications/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
