server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: ns-server
          uri: ${NS_SERVER_URI}
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        - id: auth-server
          uri: ${AUTH_SERVER_URI}
          predicates:
            - Path=/auth/**
          filters:
              - StripPrefix=0
  data:
    redis:
      host: redis
      port: 6379
jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
